version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_HOST=mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
